export const mentorSkills = [
    // --- TECHNICAL / SOFTWARE ENGINEERING ---
    { value: "web_development", label: "Web Development" },
    { value: "frontend_development", label: "Frontend Development" },
    { value: "backend_development", label: "Backend Development" },
    { value: "fullstack_development", label: "Fullstack Development" },
    { value: "mobile_development", label: "Mobile Development" },
    { value: "ios_development", label: "iOS Development" },
    { value: "android_development", label: "Android Development" },
    { value: "ui_ux_design", label: "UI/UX Design" },
    { value: "database_design", label: "Database Design" },
    { value: "sql", label: "SQL" },
    { value: "nosql", label: "NoSQL" },
    { value: "cloud_computing", label: "Cloud Computing" },
    { value: "aws", label: "AWS" },
    { value: "firebase", label: "Firebase" },
    { value: "devops", label: "DevOps" },
    { value: "version_control", label: "Version Control (Git)" },
    { value: "software_architecture", label: "Software Architecture" },
    { value: "system_design", label: "System Design" },
    { value: "api_design", label: "API Design" },
    { value: "testing_debugging", label: "Testing & Debugging" },
    { value: "performance_optimization", label: "Performance Optimization" },
    { value: "scripting", label: "Scripting (Python, Bash, etc.)" },
    { value: "game_development", label: "Game Development" },
    { value: "embedded_systems", label: "Embedded Systems" },
    { value: "robotics", label: "Robotics" },
    { value: "ar_vr", label: "AR/VR Development" },
    { value: "ai", label: "Artificial Intelligence" },
    { value: "machine_learning", label: "Machine Learning" },
    { value: "data_science", label: "Data Science" },
    { value: "data_engineering", label: "Data Engineering" },
    { value: "cybersecurity", label: "Cybersecurity" },
    { value: "blockchain", label: "Blockchain" },
    { value: "open_source", label: "Open Source Contribution" },
    { value: "technical_writing", label: "Technical Writing" },
    { value: "code_review", label: "Code Review" },
    { value: "agile_scrum", label: "Agile / Scrum Methodology" },
    { value: "ci_cd", label: "CI/CD Pipelines" },
    { value: "docker", label: "Docker / Containerization" },
    { value: "kubernetes", label: "Kubernetes" },
  
    // --- BUSINESS / FINANCE ---
    { value: "business_analysis", label: "Business Analysis" },
    { value: "financial_modeling", label: "Financial Modeling" },
    { value: "accounting", label: "Accounting" },
    { value: "budgeting", label: "Budgeting" },
    { value: "forecasting", label: "Forecasting" },
    { value: "data_visualization", label: "Data Visualization" },
    { value: "excel_advanced", label: "Advanced Excel" },
    { value: "erp_systems", label: "ERP Systems (SAP, Oracle)" },
    { value: "kpi_analysis", label: "KPI Analysis" },
    { value: "project_management", label: "Project Management" },
    { value: "strategy_consulting", label: "Strategy Consulting" },
    { value: "market_research", label: "Market Research" },
  
    // --- SUPPLY CHAIN / OPERATIONS ---
    { value: "supply_chain_management", label: "Supply Chain Management" },
    { value: "logistics", label: "Logistics" },
    { value: "inventory_management", label: "Inventory Management" },
    { value: "procurement", label: "Procurement" },
    { value: "lean_six_sigma", label: "Lean / Six Sigma" },
    { value: "operations_research", label: "Operations Research" },
    { value: "process_optimization", label: "Process Optimization" },
    { value: "demand_planning", label: "Demand Planning" },
  
    // --- PRODUCT / DESIGN ---
    { value: "product_management", label: "Product Management" },
    { value: "product_strategy", label: "Product Strategy" },
    { value: "design_thinking", label: "Design Thinking" },
    { value: "prototyping", label: "Prototyping" },
    { value: "user_research", label: "User Research" },
  
    // --- EDUCATION / COMMUNITY / MISC ---
    { value: "technical_tutoring", label: "Technical Tutoring" },
    { value: "public_speaking", label: "Public Speaking" },
    { value: "community_leadership", label: "Community Leadership" },
    { value: "workshop_facilitation", label: "Workshop Facilitation" }
  ];
  